-- CREATE TABLE IF NOT EXISTS users (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');
-- example of code (well have to create the table and add the info from the files we have)
-- docker exec -it mysql-db mysql -u root -p
-- USE mydatabase;
-- SHOW TABLES;
-- SELECT * FROM users;
