version: '3.7'
services:
    neo4j:
        hostname: neo4j
        image: neo4j:4.4.17-community
        container_name: neo4j
        environment:
            - NEO4J_dbms_mode=SINGLE
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=localhost
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_security_allow_csv_import_from_file_urls=true
            - NEO4JLABS_PLUGINS=["graph-data-science"]
        ports:
            - 7474:7474
            - 7473:7473
            - 7687:7687
        volumes:
            - ../dfs/dataout:/var/lib/neo4j/import
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
          - MYSQL_ROOT_PASSWORD= rootpassword
          - MYSQL_DATABASE= mydatabase
          - MYSQL_USER= user
          - MYSQL_PASSWORD= password
        ports:
        - "3306:3306"
        volumes:
        - ./initdb:/docker-entrypoint-initdb.d
        - ../dfs/tabular:/var/lib/mysql-files

    elasticsearch:
      image: elasticsearch:8.7.0
      container_name: elasticsearch
      ports:
        - 9200:9200
      networks:
        - connection_network 
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
networks:
  connection_network:
    external: true
    name: connection_network