version: '3.7'
services:
    neo4j:
        hostname: neo4j
        image: neo4j:4.4.17-community
        environment:
            - NEO4J_dbms_mode=SINGLE
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=localhost
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
            - NEO4J_AUTH=neo4j/password
            - NEO4JLABS_PLUGINS=["graph-data-science"]
        ports:
            - 7474:7474
            - 7473:7473
            - 7687:7687
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        ports:
        - "3306:3306"
        volumes:
        - ./initdb:/docker-entrypoint-initdb.d

    elasticsearch:
      image: elasticsearch:8.7.0
      ports:
        - 9200:9200      
      environment:
        - discovery.type=single-node
      #  - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - xpack.security.enabled=false
      #volumes:
      #  - ./es-data:/usr/share/elasticsearch/data


    # jupyter:
    #  image: jupyter/minimal-notebook
    #  ports:
    #    - 8888:8888
    #  #volumes:
    #  #  - "./notebooks:/home/jovyan/work/notebooks"
    #  command: ["start-notebook.sh","--NotebookApp.token=''","--NotebookApp.password=''"]
    # si lo montamos ahora no podremos proque spark lo está utilizando, tenemos que buscar otro mapeo o cerrar ese contenedor
